//
//  PasteboardPrivacy.swift
//  hypetype
//
//  Маркеры nspasteboard.org-конвенции (с 2011 г.) — исключают наши промежуточные
//  записи в pasteboard из истории буфера обмена: системного Spotlight Clipboard
//  History (macOS 26 Tahoe) и сторонних менеджеров (Maccy, Paste, Raycast и т.д.).
//
//  Apple не дала публичного API для опт-аута из Spotlight Clipboard History;
//  эта конвенция — единственный известный способ. Maccy и др. её гарантированно
//  уважают; уважает ли её Spotlight в Tahoe — проверяется эмпирически.
//

import AppKit

enum PasteboardPrivacy {
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    /// Пишет текст в pasteboard, помечая запись как временную/конфиденциальную/авто-сгенерированную.
    /// Для Cmd+V — обычный текст; для подписчиков changeCount — сигнал «не сохраняй в истории».
    static func writePrivate(_ text: String, to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        attachMarkers(to: item)
        pasteboard.writeObjects([item])
    }

    /// То же, но с HTML-обёрткой — для вставки одиночного пробельного символа
    /// в ProseMirror-редакторы (иначе whitespace нормализуется).
    static func writePrivateWithHTML(_ text: String, to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        // <meta charset> обязателен: без него нативный HTML-импортёр Apple Notes
        // угадывает кодировку и на русской системе берёт Windows-1251 — тогда UTF-8
        // байты неразрывного пробела (0xC2 0xA0) читаются как «В» + пробел.
        item.setString("<meta charset=\"utf-8\"><span>\(text)</span>", forType: .html)
        attachMarkers(to: item)
        pasteboard.writeObjects([item])
    }

    /// Восстанавливает в pasteboard ранее сохранённые items, но с маркерами «не пиши
    /// в историю». Для Cmd+V — оригинальные данные (текст/картинка/RTF/файлы); для
    /// Spotlight Clipboard History — сигнал «эта запись уже в истории, не дублируй».
    ///
    /// Spotlight для текста делает дедупликацию по содержимому (одинаковые строки
    /// склеиваются), а для картинок — нет (каждая запись = новый элемент в истории).
    /// Маркеры закрывают эту дырку для всех типов.
    static func restorePrivate(_ items: [NSPasteboardItem], to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        guard !items.isEmpty else { return }
        let markedItems = items.map { item -> NSPasteboardItem in
            let copy = NSPasteboardItem()
            for type in item.types {
                if let data = item.data(forType: type) {
                    copy.setData(data, forType: type)
                }
            }
            attachMarkers(to: copy)
            return copy
        }
        pasteboard.writeObjects(markedItems)
    }

    private static func attachMarkers(to item: NSPasteboardItem) {
        // Для маркеров важно наличие типа, а не payload — кладём пустые данные.
        item.setData(Data(), forType: transient)
        item.setData(Data(), forType: concealed)
        item.setData(Data(), forType: autoGenerated)
    }
}
